version: '3.8'

services:
  text-extraction-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./uploads:/app/uploads
    environment:
      - MAX_WORKERS=4
      - LOG_LEVEL=info

# Dockerfile contents:
# ==================

# FROM python:3.9-slim
# 
# # Install system dependencies including Tesseract OCR and poppler-utils (for pdf2image)
# RUN apt-get update && apt-get install -y \
#     tesseract-ocr \
#     tesseract-ocr-eng \
#     poppler-utils \
#     libreoffice \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*
# 
# WORKDIR /app
# 
# # Copy requirements file and install dependencies
# COPY app/requirements.txt /app/
# RUN pip install --no-cache-dir -r requirements.txt
# 
# # Create uploads directory
# RUN mkdir -p /app/uploads
# 
# # Copy application code
# COPY app /app/
# 
# # Command to run the application
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]