services:
  text-extraction-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./uploads:/app/uploads
      - docling_cache:/root/.cache/docling/models
    environment:
      - MAX_WORKERS=4
      - LOG_LEVEL=info
      - API_KEY=${API_KEY:-your-default-api-key-here}  # Set this in .env file or environment
      - DOCLING_ARTIFACTS_PATH=/root/.cache/docling/models

volumes:
  docling_cache:  # Persistent volume for Docling models